### ISSUE TITLE
Make encoding tests fails

### ISSUE THREAD

**Issue by GoogleCodeExporter** [peterhelin/pydelicious#1]
```
What steps will reproduce the problem?
1. $ python pydelicioustest.py
Username (hit return to skip api test):[username]
Passwd (hit return to skip api test):[password]

What is the expected output? What do you see instead?
Expected test success. instead saw

.............EE.....
======================================================================
ERROR: teststr2uni (__main__.TestHelperFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pydelicioustest.py", line 34, in teststr2uni
    t = {'a':u'a', u'a':u'a', 'ä':u'\xe4', u'ä':u'\xe4'}
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal
not in range(128)

======================================================================
ERROR: teststr2utf8 (__main__.TestHelperFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "pydelicioustest.py", line 38, in teststr2utf8
    t = {'a':'a', u'a':'a', 'ä':'\xc3\xa4', u'ä':'\xc3\xa4'}
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal
not in range(128)

----------------------------------------------------------------------
Ran 20 tests in 136.757s

FAILED (errors=2)



What version of the product are you using? On what operating system?

Downloaded from SVN today. Ran on cygwin using Python 2.5b2.

Please provide any additional information below.

Currently seeing 10 errors in Windows tests with 2.4.2 as well, but have
not yet had time to examine them.
```

Original issue reported on code.google.com by `holden...@gmail.com` on 20 Sep 2006 at 4:31

**Comment by GoogleCodeExporter** [comment]
```
Sorry about the lack of a meaningful summary title.
```

Original comment by `holden...@gmail.com` on 20 Sep 2006 at 4:32

**Comment by GoogleCodeExporter** [comment]
```
Unicode isn't my specialty.  Hopefully this project will get some super-powered
unicode developers one day to address this one ;-)  I'll take a look though but 
don't
expect too much :-(

Do post your 10 errors in Windows tests with 2.4.2 in a seperate issue and 
hopefully
I'll be smarter on those issues
```

Original comment by `gregpin...@gmail.com` on 20 Sep 2006 at 10:07
- Changed title: **Not sure if I can help with this one.**

**Comment by GoogleCodeExporter** [comment]
```
These functions have been removed and encodings tests should run OK now (but 
not by
default, run 'make test-server' to run blackbox tests against server).

Closing because fixed.
```

Original comment by `berend.v...@gmail.com` on 28 Nov 2008 at 3:50
- Changed title: **Make encoding tests fails**
- Changed state: **Fixed**
