### ISSUE TITLE
New delicious post-Avos breaks pydelicious?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [peterhelin/pydelicious#40]
```
What steps will reproduce the problem?
1. clean Amazon instance with Python 2.6.6
2. sudo easy_install pydelicious
3. dlcs -u <username>

What is the expected output? What do you see instead?
Errors as:

Save password to config (/home/ramana/.dlcs-rc)? [Y]es/No: n
Traceback (most recent call last):
  File "/usr/bin/dlcs", line 9, in <module>
    load_entry_point('pydelicious==0.6', 'console_scripts', 'dlcs')()
  File "/usr/lib/python2.6/site-packages/pydelicious-0.6-py2.6.egg/pydelicious/tools/dlcs.py", line 1196, in _main
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/python2.6/site-packages/pydelicious-0.6-py2.6.egg/pydelicious/tools/dlcs.py", line 427, in main
    return cmd(conf, dlcs, *args, **options)
  File "/usr/lib/python2.6/site-packages/pydelicious-0.6-py2.6.egg/pydelicious/tools/dlcs.py", line 471, in info
    u = dlcs.posts_update()['update']['time']
  File "/usr/lib/python2.6/site-packages/pydelicious-0.6-py2.6.egg/pydelicious/__init__.py", line 785, in posts_update
    return self.request("posts/update", **kwds)
  File "/usr/lib/python2.6/site-packages/pydelicious-0.6-py2.6.egg/pydelicious/__init__.py", line 718, in request
    fl = self._api_request(path, params=params, opener=self._opener)
  File "/usr/lib/python2.6/site-packages/pydelicious-0.6-py2.6.egg/pydelicious/__init__.py", line 304, in dlcs_api_request
    fl = http_request(url, opener=opener)
  File "/usr/lib/python2.6/site-packages/pydelicious-0.6-py2.6.egg/pydelicious/__init__.py", line 224, in http_request
    return opener.open(request)
  File "/usr/lib/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.6/urllib2.py", line 429, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/site-packages/pydelicious-0.6-py2.6.egg/pydelicious/__init__.py", line 183, in http_error_401
    raise PyDeliciousUnauthorized, "Check credentials."
pydelicious.PyDeliciousUnauthorized: Check credentials.

What version of the product are you using? On what operating system?
0.6, Python 2.6.6, CentOS 5.x

Please provide any additional information below.


```

Original issue reported on code.google.com by `tree...@gmail.com` on 29 Sep 2011 at 12:38

**Comment by GoogleCodeExporter** [comment]
```
curl calls on the API seem to work, and I was getting this error with a python 
script I'd written this week.  The script definitely worked last week.
```

Original comment by `tree...@gmail.com` on 29 Sep 2011 at 12:40

**Comment by GoogleCodeExporter** [comment]
```
Same error, but from my web app: 

The code:

from pydelicious import DeliciousAPI
[...]
delicious = DeliciousAPI(settings.DELICIOUS_USER, settings.DELICIOUS_PWD)

delicious.posts_add(url=self.url,
    description=self.title,
    extended=strip_tags(self.description_html),
    tags=self.tags,
    dt=self.posted_iso(),
    replace=True)

This defintely worked on Sept 21st but broke as of AVOS relaunch (on Sept 27th)

part of the stack trace:

[...]
File "/home/userid/lib/python2.5/pydelicious/__init__.py", line 842, in 
posts_add
   replace=replace, shared=shared, **kwds)

 File "/home/userid/lib/python2.5/pydelicious/__init__.py", line 660, in request
   fl = self._api_request(path, params=params, opener=self._opener)

 File "/home/userid/lib/python2.5/pydelicious/__init__.py", line 303, in dlcs_api_request
   fl = http_request(url, opener=opener)

 File "/home/userid/lib/python2.5/pydelicious/__init__.py", line 223, in http_request
   return opener.open(request)

 File "/usr/local/lib/python2.5/urllib2.py", line 387, in open
   response = meth(req, response)

 File "/usr/local/lib/python2.5/urllib2.py", line 498, in http_response
   'http', request, response, code, msg, hdrs)

 File "/usr/local/lib/python2.5/urllib2.py", line 419, in error
   result = self._call_chain(*args)

 File "/usr/local/lib/python2.5/urllib2.py", line 360, in _call_chain
   result = func(*args)

 File "/home/userid/lib/python2.5/pydelicious/__init__.py", line 182, in http_error_401
   raise PyDeliciousUnauthorized, "Check credentials."

PyDeliciousUnauthorized: Check credentials.

pydelicious 0.6 and python 2.5.?
```

Original comment by `p.maric...@gmail.com` on 29 Sep 2011 at 8:17

**Comment by GoogleCodeExporter** [comment]
```
Perhaps should have given it the week before reporting for AVOS to straighten 
themselves out.   This issue isn't happening anymore.
```

Original comment by `tree...@gmail.com` on 4 Oct 2011 at 4:46
