### ISSUE TITLE
Cannot install using Python 3.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [peterhelin/pydelicious#43]
```
What steps will reproduce the problem?
1. Download the package
2. Open terminal
3. Go to the directory where the file is placed and unzip it
4. Run "python setup.py install"

What is the expected output? What do you see instead?
Expected to install, however this is the current output:

daniel@dqo:pydelicious - [ruby-1.9.2 - (master) $ ]$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import pydelicious
  File "/Users/daniel/Documents/lang/python/pydelicious/pydelicious/__init__.py", line 171
    raise DeliciousItemExistsError, params['url']
                                  ^
SyntaxError: invalid syntax

What version of the product are you using? On what operating system?
Python 3.2.3 (default, Apr 19 2012, 01:32:56) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)] on darwin

Please provide any additional information below.

```

Original issue reported on code.google.com by `danie...@gmail.com` on 6 Jan 2013 at 3:53

**Comment by GoogleCodeExporter** [comment]
```
i also met this problem:
Python 3.3   windows 7
```

Original comment by `liuluo...@gmail.com` on 4 Apr 2013 at 9:49

**Comment by GoogleCodeExporter** [comment]
```
i got the same problem, python 3.3 windows 7
```

Original comment by `zh1985...@gmail.com` on 23 Apr 2013 at 2:52

**Comment by GoogleCodeExporter** [comment]
```
..me too... help me..
```

Original comment by `hyeoksu....@gmail.com` on 24 Apr 2013 at 4:40

**Comment by GoogleCodeExporter** [comment]
```
i also meet this problem,who can help me?
```

Original comment by `wbgle...@gmail.com` on 13 Sep 2013 at 10:43

**Comment by GoogleCodeExporter** [comment]
```
Hi, I am getting the same error.. Is the issue resolved ? 


```

Original comment by `newtonlo...@gmail.com` on 15 Jan 2014 at 1:45

**Comment by GoogleCodeExporter** [comment]
```
Ops !!.. Win 7 too.. 
```

Original comment by `jonnygua...@gmail.com` on 13 Mar 2014 at 5:19

**Comment by GoogleCodeExporter** [comment]
```
Win8.1, Python3.4
can not install
```

Original comment by `Navono...@gmail.com` on 29 Mar 2014 at 10:30

**Comment by GoogleCodeExporter** [comment]
```
Win 7, Python 3.4
I am getting similar error... 
Any update on whether this defect is fixed?
```

Original comment by `vsubasre...@gmail.com` on 22 Jun 2014 at 10:40

**Comment by GoogleCodeExporter** [comment]
```
windows 7 
Python 3.4 

```

Original comment by `niharkan...@gmail.com` on 6 Jul 2014 at 4:48

**Comment by GoogleCodeExporter** [comment]
```
Definitely same error with win8 py3.4
Someone knows any ideas to solve this? 
```

Original comment by `kkbn...@gmail.com` on 26 Jul 2014 at 9:26

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Guys, it's not a bug, it's kind of feature since the library was written for 
python 2.x, so there must be troubles with incompatible printing, formats and 
syntax in python 3.x

I'm not a developer of pydelicious and I have no connection with them but I'm 
an interested user and I ported it for python 3.x.

[SOLUTION]
Just replace file pydelicious/__init__.py with the one I attached and then 
rerun setup as in the manual. 

```

Original comment by `timur.r....@gmail.com` on 18 Aug 2014 at 5:48

Attachments:
- [**init**.py](https://storage.googleapis.com/google-code-attachments/pydelicious/issue-43/comment-12/__init__.py)
